### ISSUE TITLE
Portainer is not able to download extensions manifest on clean HassOS install

### ISSUE THREAD

**Issue by joaomlneto** [hassio-addons/addon-portainer#130]
This is a re-reporting of #115, given that the upstream project (hassio-os) told me it's not their problem (see https://github.com/home-assistant/operating-system/issues/1446) and that I didn't get any reply from @frenck on #115 .

I'd ask @frenck (and other collaborators) to not tell me to fuck off without any further dialogue. If it's not here, just help me know where this belongs.
While I know and appreciate that you provide your time for free, I'm also here letting you know of an issue for free and want to help out. Please do provide pointers on where to report this issue.

Additional details are in #115 and https://github.com/home-assistant/operating-system/issues/1446 . Not really willing to bother to summarize things here at this point, since I guess you'll just close this. Ask away if you want.

**Comment by frenck** [comment]
The add-on is not responsible for providing internet. Sorry, but even if I wanted to, from an add-on perspective, there is nothing I can do.

**Comment by joaomlneto** [comment]
There is internet connectivity. It's just the Portainer add-on that cannot connect to the Internet.

It's specific to how this add-on is being installed on a vanilla installation of hassio-os on the most standard hardware (RPi4).

The Operating System works fine. Home Assistant can update itself. 

It's. Just. This.

**Comment by frenck** [comment]
> It's just the Portainer add-on that cannot connect to the Internet.
 
Thanks for the downvote, and I'm on repeat now, there is nothing the add-on does or control about connectivity. That is not a responsibility of the add-on on something the add-on interferes with at any point. There is absolutely 0 code or settings around this or anything that the add-on can do to adjust.

I'm sorry to hear you want me to perform magic, but I can't. I'm sorry to hear you are experiencing it as: "to not tell me to fuck off without any further dialogue", however, you are forcing me into a debug session with stuff that is really not my problem, care about or want to waste my time on; Simply because of the above, the add-on does not provide, is responsible for or configures network connectivity at all.

You are the first and only to report this as well in about ~20K instances.

It's. Just. This.
