### ISSUE TITLE
Cant install on latest version: This add-on is not available on your system.

### ISSUE THREAD

**Issue by dogmatic69** [hassio-addons/addon-portainer#21]
# Problem/Motivation

I can not install this on a recent version of hassio

## Expected behavior

I should be able to install it

## Actual behavior

![image](https://user-images.githubusercontent.com/94674/60622670-22e2c480-9de1-11e9-93a3-72f8cd1a5a60.png)

## Steps to reproduce

Run hassio > 0.90 and this is not installable

**Comment by sinclairpaul** [comment]
Please confirm the version of HA you are running and the hardware platform.  You will need 0.93 or higher.

**Comment by frenck** [comment]
The only requirement this add-on has: Home Assistant 0.92.0b2 or newer. All Hass.io supported hardware platforms are supported by this add-on.

This is due to this add-on relies on using the Ingress feature which was first introduced in 0.92 

Code reference if interested: <https://github.com/hassio-addons/addon-portainer/blob/master/portainer/config.json#L12>
